### ISSUE TITLE
Error After Update 

### ISSUE THREAD

**Issue by thechris1992** [naofireblade/homebridge-weather-plus#119]
Loaded plugin: homebridge-weather-plus

====================
ERROR INITIALIZING PLUGIN homebridge-weather-plus:
Error: Package exports for '/usr/local/lib/node_modules/homebridge-weather-plus/node_modules/googleapis-common/node_modules/uuid' do not define a '.' subpath
at resolveExports (internal/modules/cjs/loader.js:419:17)
at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
at Function.Module._load (internal/modules/cjs/loader.js:693:27)
at Module.require (internal/modules/cjs/loader.js:864:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-weather-plus/node_modules/googleapis-common/build/src/apirequest.js:19:14)
at Module._compile (internal/modules/cjs/loader.js:971:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
at Module.load (internal/modules/cjs/loader.js:822:32)
at Function.Module._load (internal/modules/cjs/loader.js:730:14)
at Module.require (internal/modules/cjs/loader.js:864:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-weather-plus/node_modules/googleapis-common/build/src/index.js:23:20)
at Module._compile (internal/modules/cjs/loader.js:971:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)

Node JS: v13.0.1
NPM Version: v6.14.5
Homebridge Version: 1.0.4

**Comment by naofireblade** [comment]
Might be a problem with your node js version. Looks like you are neither on latest (14.x) nor LTS (12.x) node js version.

**Comment by thechris1992** [comment]
So witch one is the best, working one?

**Comment by naofireblade** [comment]
Both nodejs versions should work. LTS 12 (Long term support) is good if you don’t want to hassle with major updates every few months.
Latest 14 is good if you want the latest features of nodejs.
I‘m running v12.

npm version should not matter.

**Comment by thechris1992** [comment]
Okay, i installed Node JS 14.2.0 and it works fine.
