### ISSUE TITLE
Issue with "compatibility": "eve2" 

### ISSUE THREAD

**Issue by JacVid** [naofireblade/homebridge-weather-plus#146]
Hello,

when compatibility is set to eve2, the plugin doesn't work. When it is set to eve or both, it works perfectly.

What did I do wrong ?

Here's the log
[WeatherPlus] Adding station with weather service OpenWeatherMap named 'Aujourd'hui'
12/06/2020 à 20:14:28 ReferenceError: CustomService is not defined
    at new ForecastWeatherAccessory (/home/hoobs/.hoobs/node_modules/homebridge-weather-plus/accessories/forecast.js:54:30)
    at /home/hoobs/.hoobs/node_modules/homebridge-weather-plus/index.js:99:31
    at Array.forEach (<anonymous>:null:null)
    at /home/hoobs/.hoobs/node_modules/homebridge-weather-plus/index.js:93:19
    at Array.forEach (<anonymous>:null:null)
    at new WeatherPlusPlatform (/home/hoobs/.hoobs/node_modules/homebridge-weather-plus/index.js:64:22)
    at Server.loadPlatforms (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:283:34)
    at Server.run (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/@hoobs/hoobs/bin/hoobs:95:81)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11

**Comment by mat130780** [comment]
same here when I select Eve (with grouping).

**Comment by naofireblade** [comment]
Fixed in v3.2.4
