### ISSUE TITLE
Error/crashing with OpenWeatherMap

### ISSUE THREAD

**Issue by morphix9** [naofireblade/homebridge-weather-plus#152]
```
[7/23/2020, 10:31:23] [WeatherPlus] Error retrieving weather report
[7/23/2020, 10:31:23] [WeatherPlus] Error: getaddrinfo EAI_AGAIN api.openweathermap.org
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26) {
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.openweathermap.org'
}
[7/23/2020, 10:31:23] [WeatherPlus] undefined
```

**Comment by vsenn** [comment]
Hi! I've got the same issue starting today. Even, it this could be a DNS issue that would be great to catch that exception and not impact other accessories on same instance. Thanks in advance.

[8/21/2021, 2:32:45 PM] [WeatherPlus] Error retrieving weather report
[8/21/2021, 2:32:45 PM] [WeatherPlus] Error: getaddrinfo EAI_AGAIN api.openweathermap.org
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.openweathermap.org'
}
[8/21/2021, 2:32:45 PM] [WeatherPlus] undefined
[8/21/2021, 2:36:45 PM] [WeatherPlus] Error retrieving weather report
[8/21/2021, 2:36:45 PM] [WeatherPlus] Error: getaddrinfo EAI_AGAIN api.openweathermap.org
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.openweathermap.org'
}
[8/21/2021, 2:36:45 PM] [WeatherPlus] undefined
