### ISSUE TITLE
Observation time issue with HomeBridge 1.3.0

### ISSUE THREAD

**Issue by salmundo11** [naofireblade/homebridge-weather-plus#186]
`[homebridge-weather-plus] This plugin threw an error from the characteristic 'Observation Time': Error: characteristic value expected string and received object
    at CustomCharacteristic.ObservationTime.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1987:17)
    at CustomCharacteristic.ObservationTime.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1257:20)
    at TemperatureSensor.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:459:35)
    at WeatherPlusPlatform.saveCharacteristic (/usr/local/lib/node_modules/homebridge-weather-plus/index.js:423:24)
    at /usr/local/lib/node_modules/homebridge-weather-plus/index.js:247:15
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-weather-plus/index.js:245:39
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-weather-plus/index.js:234:27
    at WundergroundAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-weather-plus/apis/weatherunderground.js:56:7) See https://git.io/JtMGR for more info.`

**Comment by NorthernMan54** [comment]
@salmundo11 Question did homebridge 1.3.0 continue to work for you or did you need to rollback ?

**Comment by salmundo11** [comment]
I’ve disabled the plugin and am working with 1.3.0. I can enable the plugin and test to see its impact.

**Comment by naofireblade** [comment]
This was fixed in v3.2.5 as well.
