### ISSUE TITLE
Plugin suddenly doesn't work anymore

### ISSUE THREAD

**Issue by Funskes** [naofireblade/homebridge-weather-plus#203]
Nothing has changed and I suddenly get this message.
> [13/06/2021, 17:30:40] [WeatherPlus] Error retrieving weather report
[13/06/2021, 17:30:40] [WeatherPlus] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/local/lib/node_modules/homebridge-weather-plus/apis/openweathermap.js:246:21)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-weather-plus/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-weather-plus/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-weather-plus/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-weather-plus/node_modules/request/request.js:993:23)
[13/06/2021, 17:30:40] [WeatherPlus] undefined
[14/06/2021, 01:10:06] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
![Schermafbeelding 2021-06-14 om 11 05 37](https://user-images.githubusercontent.com/58253773/121867659-7a457b00-cd00-11eb-9786-3fef23bb21fa.jpg)
I have already done a restart, but the message still comes back.

**Comment by facundo59** [comment]
Ah so I am not the only one.

**Comment by Funskes** [comment]
@facundo59 
I've loaded homebridge-weather-plus v3.2.6 as a child bridge and it looks like this is working successfully!

**Comment by nov-** [comment]
> @facundo59
> I've loaded homebridge-weather-plus v3.2.6 as a child bridge and it looks like this is working successfully!

how do you do that?

**Comment by Funskes** [comment]
> how do you do that?

I've installed this Homebridge and with this a can create a child bridge

**Comment by dacarson** [comment]
I have migrated to a new URL request framework, axios package, which I hope will give more informed error messages. 
If you see this issue still, please file a new report.
