### ISSUE TITLE
Homebridge on RPi

### ISSUE THREAD

**Issue by loganprieto32** [naofireblade/homebridge-weather-plus#214]
`====================
[17/08/2021, 09:58:17] ERROR LOADING PLUGIN homebridge-weather-plus:
[17/08/2021, 09:58:17] Error: Cannot find module 'geo-tz'
Require stack:
- /usr/local/lib/node_modules/homebridge-weather-plus/apis/openweathermap.js
- /usr/local/lib/node_modules/homebridge-weather-plus/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-weather-plus/apis/openweathermap.js:6:10)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
[17/08/2021, 09:58:17] ====================`

**Comment by RichKenyon** [comment]
I'm getting the same error on RPi. Running Node.js v16.13.0 and NPM v8.1.0.

I'm using Homebridge UI but will try to set up remote SSH to diagnose further.

**Comment by dacarson** [comment]
No new comments for a while. Assume that it is now working ok.
