### ISSUE TITLE
Problem to loaded api

### ISSUE THREAD

**Issue by slaw47** [naofireblade/homebridge-weather-plus#223]
[23/11/2021, 09:55:17] Loaded plugin: homebridge-weather-plus@3.2.6
[23/11/2021, 09:55:19] ====================
[23/11/2021, 09:55:19] ERROR INITIALIZING PLUGIN homebridge-weather-plus:
[23/11/2021, 09:55:19] /usr/local/lib/node_modules/homebridge-weather-plus/node_modules/googleapis/build/src/apis/appengine/v1beta.js:505
         !  }
            ^

SyntaxError: Unexpected token '}'
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-weather-plus/node_modules/googleapis/build/src/apis/appengine/index.js:22:18)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-weather-plus/node_modules/googleapis/build/src/apis/index.js:39:21)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-weather-plus/node_modules/googleapis/build/src/googleapis.js:16:16)
[23/11/2021, 09:55:19] ====================
[23/11/2021, 09:55:19] ---
[23/11/2021, 09:55:19] Loading 4 platforms...
[23/11/2021, 09:55:19] [Config] Initializing config platform...
[23/11/2021, 09:55:19] [Config] Running in Service Mode
[23/11/2021, 09:55:19] No plugin was found for the platform "WeatherPlus" in your config.json. Please make sure the corresponding plugin is installed correctly.

**Comment by dacarson** [comment]
I realize this is an old report. I am working on cleaning up issues for this plugin. 
Can you tell me if you were able to solve this issue?

**Comment by dacarson** [comment]
Closing as stale.
