### ISSUE TITLE
Support for Homebridge 2.0

### ISSUE THREAD

**Issue by rionshin** [naofireblade/homebridge-weather-plus#301]
Soon Homebridge 2.0 will be released which will have some break changes to plugins. 
could you please check is this plugin is impacted and make it working with 2.0 

https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

**Comment by jonad2002** [comment]
Testing with 2.0 B11 results:

[8/10/2024, 1:30:09 PM][homebridge-weather-plus]Adding station with weather service OpenWeatherMap named 'Home'
/var/lib/homebridge/node_modules/homebridge-weather-plus/util/characteristics.js:173
                Characteristic.call(this, 'Air Pressure', CustomUUID.AirPressure);
                 ^
TypeError: Class constructor Characteristic cannot be invoked without 'new'
    at new CustomCharacteristic.AirPressure (/var/lib/homebridge/node_modules/homebridge-weather-plus/util/characteristics.js:173:18)
    at TemperatureSensor.addCharacteristic (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:518:57)
    at /var/lib/homebridge/node_modules/homebridge-weather-plus/accessories/currentConditions.js:140:35
    at Array.forEach (<anonymous>)
    at new CurrentConditionsWeatherAccessory (/var/lib/homebridge/node_modules/homebridge-weather-plus/accessories/currentConditions.js:68:61)
    at /var/lib/homebridge/node_modules/homebridge-weather-plus/index.js:94:30
    at Array.forEach (<anonymous>)
    at new WeatherPlusPlatform (/var/lib/homebridge/node_modules/homebridge-weather-plus/index.js:65:22)
    at ChildBridgeFork.startBridge (/var/lib/homebridge/node_modules/homebridge/src/childBridgeFork.ts:155:42)

**Comment by fubu2k** [comment]
Same error in Homebridge 2.0 beta 21. The Plugin needs an update.

**Comment by dacarson** [comment]
I am starting to look at this now.
It is probably also a good time to address: #150 Move off deprecated 'request' module

**Comment by dacarson** [comment]
Landed fixes for #150. Can now look at Homebridge 2.0

**Comment by dacarson** [comment]
With current checked in code, it is working but I get these errors:
```
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Wind Speed: 5.06 mph'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Wind Dir: WNW'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('UV Index: null'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
HAP-NodeJS WARNING: The accessory 'Configured Name' has an invalid 'ConfiguredName' characteristic ('Air Pressure: 1014.6 hPa'). Please use only alphanumeric, space, and apostrophe characters. Ensure it starts and ends with an alphabetic or numeric character, and avoid emojis. This may prevent the accessory from being added in the Home App or cause unresponsiveness.
```
I have filed a support ticket with Homebridge here https://github.com/homebridge/HAP-NodeJS/issues/1079
